// GitHub Pages reads the latest public snapshots generated by GitHub Actions.
// The OpenDART key is never included in this browser bundle.
const isGitHubPages = window.location.hostname.endsWith('github.io');
window.POSCO_API_BASE_URL = window.POSCO_API_BASE_URL || (isGitHubPages ? '' : 'http://localhost:8000');
window.POSCO_STATIC_DART = isGitHubPages;
